version: "3.8"

services:
  frontend:
    build: ./frontend/frontend-next
    container_name: studycafe-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: studycafe-backend
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - FILE_UPLOAD_PATH=/study_uploads
    volumes:
      - ./uploads:/study_uploads

  redis:
    image: redis:7.2
    container_name: studycafe-redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0
    container_name: studycafe-mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=studycafe
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
